-- Seed 20 Travel Packages - Matching Actual Table Structure

INSERT INTO packages (id, title, slug, description, short_description, price, currency, duration, duration_unit, destination, included, excluded, highlights, availability, max_participants, featured, status, view_count, inquiry_count, categories, created_at, updated_at) VALUES
('pkg-001', 'Bali Paradise - 5 Days', 'bali-paradise-5-days', 'Experience authentic Balinese culture with temple visits, beach relaxation, and traditional villages. Visit Tanah Lot, Ubud Rice Terraces, and enjoy traditional dance performances.', '5-day cultural tour exploring temples and beaches', 7500000, 'IDR', 5, 'days', 'Bali', '["Accommodation","Breakfast","Guide","Entrance Tickets"]', '["International Flights","Lunch","Dinner"]', '["Tanah Lot Temple","Ubud Rice Terraces","Traditional Dance Show"]', 'Daily departures', 15, 1, 'published', 156, 23, '["Beach","Culture"]', datetime('now'), datetime('now')),

('pkg-002', 'Raja Ampat Diving - 7 Days', 'raja-ampat-diving-7-days', 'World-class diving in the most biodiverse marine area. See manta rays, pristine coral reefs, and explore hidden lagoons in this remote paradise.', '7-day diving expedition in Raja Ampat', 25000000, 'IDR', 7, 'days', 'Diving', 'Raja Ampat', 'Domestic Flights, Liveaboard, All Meals, 10+ Dives, Equipment, Guide', 'International Flights, Nitrox, Tips', '10+ Dive Sites, Manta Rays, Pristine Coral Reefs, Piaynemo Viewpoint', 'Weekly departures', 10, 'Moderate', 1, 'published', 89, 12, datetime('now'), datetime('now')),

('pkg-003', 'Komodo Island Trek - 3 Days', 'komodo-island-trekking', 'Trek to see legendary Komodo dragons in their natural habitat. Snorkel at Pink Beach, climb Padar Island for stunning views.', '3-day adventure to see Komodo dragons', 4500000, 'IDR', 3, 'days', 'Adventure', 'Labuan Bajo', 'Boat Charter, All Meals, Snorkeling Equipment, Park Fees, Guide', 'Hotel in Labuan Bajo, Flights, Drinks', 'Komodo Dragons, Pink Beach, Manta Point, Padar Island Viewpoint', 'Daily departures', 12, 'Moderate', 1, 'published', 234, 45, datetime('now'), datetime('now')),

('pkg-004', 'Bromo Sunrise Tour - 2 Days', 'bromo-sunrise-tour', 'Witness magical sunrise at Mount Bromo crater. Ride jeep across volcanic sand sea and explore the stunning landscape.', '2-day sunrise tour at Mount Bromo', 2500000, 'IDR', 2, 'days', 'Mountain', 'Malang', 'Transport, Hotel, Breakfast, Jeep Safari, Guide', 'Flights, Lunch, Dinner, Horse Rental', 'Sunrise Viewpoint, Crater Trek, Jeep Safari, Sand Sea', 'Daily departures', 20, 'Easy', 0, 'published', 312, 67, datetime('now'), datetime('now')),

('pkg-005', 'Yogyakarta Heritage - 4 Days', 'yogyakarta-heritage-4-days', 'Explore ancient temples of Borobudur and Prambanan, learn batik making, and visit the Sultan palace.', '4-day cultural heritage tour', 3800000, 'IDR', 4, 'days', 'Culture', 'Yogyakarta', 'Hotel, Breakfast, Transport, Temple Tickets, Batik Workshop', 'Flights, Lunch, Dinner, Shopping', 'Borobudur Temple, Prambanan Temple, Batik Making, Kraton Palace', 'Daily departures', 18, 'Easy', 1, 'published', 421, 89, datetime('now'), datetime('now')),

('pkg-006', 'Lombok Beach Escape - 5 Days', 'lombok-beach-escape', 'Relax on pristine beaches, hike to waterfalls, and explore the peaceful beauty of Lombok island.', '5-day beach and nature getaway', 5200000, 'IDR', 5, 'days', 'Beach', 'Lombok', 'Hotel, Breakfast, Transport, Boat to Gili, Waterfall Trek', 'Flights, Meals, Water Activities', 'Senggigi Beach, Tiu Kelep Waterfall, Gili Islands, Local Villages', 'Daily departures', 16, 'Easy', 0, 'published', 178, 34, datetime('now'), datetime('now')),

('pkg-007', 'Lake Toba Highland - 4 Days', 'lake-toba-highland', 'Discover the beauty of Lake Toba, largest volcanic lake in the world. Visit Batak villages and enjoy cool mountain air.', '4-day highland lake adventure', 4200000, 'IDR', 4, 'days', 'Nature', 'North Sumatra', 'Hotel, Breakfast, Ferry, Guide, Village Tours', 'Flights, Lunch, Dinner, Shopping', 'Lake Toba Cruise, Samosir Island, Batak Traditional Houses, Hot Springs', 'Daily departures', 15, 'Easy', 0, 'published', 145, 28, datetime('now'), datetime('now')),

('pkg-008', 'Gili Islands Hopping - 3 Days', 'gili-islands-hopping', 'Explore three paradise islands: Gili Trawangan, Gili Meno, and Gili Air. Snorkel with turtles and enjoy beach life.', '3-day island hopping adventure', 3500000, 'IDR', 3, 'days', 'Beach', 'Gili Islands', 'Hotel, Breakfast, Boat Transfers, Snorkeling Equipment', 'Flights, Lunch, Dinner, Bicycle Rental', 'Island Hopping, Turtle Snorkeling, Beach Party, Sunset Views', 'Daily departures', 14, 'Easy', 1, 'published', 267, 52, datetime('now'), datetime('now')),

('pkg-009', 'Toraja Funeral Ceremony - 5 Days', 'toraja-funeral-ceremony', 'Witness unique Torajan culture and traditional funeral ceremonies in the highlands of Sulawesi.', '5-day cultural immersion in Tana Toraja', 6800000, 'IDR', 5, 'days', 'Culture', 'Tana Toraja', 'Hotel, All Meals, Transport, Guide, Village Fees', 'Flights, Ceremony Offerings, Tips', 'Funeral Ceremony, Tongkonan Houses, Rock Graves, Buffalo Market', 'Selected dates', 12, 'Moderate', 0, 'published', 98, 15, datetime('now'), datetime('now')),

('pkg-010', 'Banda Islands Spice Route - 6 Days', 'banda-islands-spice', 'Follow the historical spice trade route. Dive in pristine waters and explore colonial forts from Dutch era.', '6-day historical and diving tour', 12000000, 'IDR', 6, 'days', 'History', 'Banda Islands', 'Flights, Hotel, All Meals, Diving, Fort Tours', 'Personal Expenses, Tips, Extra Dives', 'Spice Plantations, Fort Belgica, Diving Sites, Nutmeg Processing', 'Weekly departures', 10, 'Moderate', 0, 'published', 67, 9, datetime('now'), datetime('now')),

('pkg-011', 'Java Coffee Trail - 4 Days', 'java-coffee-trail', 'Journey through Java coffee plantations. Learn the roasting process and taste premium arabica beans.', '4-day coffee culture tour', 3200000, 'IDR', 4, 'days', 'Culture', 'Central Java', 'Hotel, Breakfast, Plantation Tours, Roasting Workshop, Coffee Samples', 'Flights, Lunch, Dinner, Coffee Purchase', 'Coffee Plantation Tour, Roasting Workshop, Tasting Sessions, Village Visit', 'Daily departures', 15, 'Easy', 0, 'published', 123, 21, datetime('now'), datetime('now')),

('pkg-012', 'Nias Island Surfing - 5 Days', 'nias-island-surfing', 'Catch world-class waves at Lagundri Bay. Experience traditional stone jumping ceremony.', '5-day surfing and culture trip', 5800000, 'IDR', 5, 'days', 'Adventure', 'Nias Island', 'Hotel, Breakfast, Boat to Surf Spots, Guide', 'Flights, Surfboard Rental, Meals, Surf Lessons', 'Lagundri Bay Surf, Stone Jumping, Traditional Villages, Beach Time', 'Daily departures', 12, 'Moderate', 0, 'published', 89, 14, datetime('now'), datetime('now')),

('pkg-013', 'Thousand Islands Snorkeling - 2 Days', 'thousand-islands-snorkeling', 'Quick getaway from Jakarta to pristine islands with excellent snorkeling and beach time.', '2-day island escape from Jakarta', 2800000, 'IDR', 2, 'days', 'Beach', 'Thousand Islands', 'Boat, Cottage, Meals, Snorkeling Equipment, BBQ', 'Transport to Marina, Extra Activities', 'Coral Snorkeling, Island Hopping, Beach BBQ, Kayaking', 'Daily departures', 16, 'Easy', 0, 'published', 234, 48, datetime('now'), datetime('now')),

('pkg-014', 'Belitung Island Granite - 4 Days', 'belitung-granite-beaches', 'Explore stunning granite rock formations and pristine beaches featured in Indonesian movies.', '4-day island photography tour', 4800000, 'IDR', 4, 'days', 'Beach', 'Belitung', 'Hotel, Breakfast, Boat Tours, Guide', 'Flights, Lunch, Dinner, Photography Gear', 'Tanjung Tinggi Beach, Island Hopping, Granite Rocks, Laskar Pelangi School', 'Daily departures', 14, 'Easy', 1, 'published', 156, 29, datetime('now'), datetime('now')),

('pkg-015', 'Papua Tribal Expedition - 8 Days', 'papua-tribal-expedition', 'Deep expedition into Papua highlands to meet Dani tribe and experience ancient culture.', '8-day tribal culture expedition', 28000000, 'IDR', 8, 'days', 'Culture', 'Wamena', 'Flights, Accommodation, All Meals, Guide, Permits, Village Fees', 'Personal Gear, Tips, Ceremony Offerings', 'Dani Tribe Visit, Baliem Valley, Traditional Ceremonies, Mummy Cave', 'Selected dates', 8, 'Challenging', 0, 'draft', 34, 3, datetime('now'), datetime('now')),

('pkg-016', 'Malang City & Beaches - 3 Days', 'malang-city-beaches', 'Explore colorful Malang city, visit apple orchards, and relax at southern beaches.', '3-day city and beach combo', 3100000, 'IDR', 3, 'days', 'City', 'Malang', 'Hotel, Breakfast, Transport, Entrance Tickets', 'Flights, Meals, Shopping, Beach Activities', 'Colorful Village, Apple Picking, Beach Visit, City Tour', 'Daily departures', 16, 'Easy', 0, 'published', 189, 37, datetime('now'), datetime('now')),

('pkg-017', 'Derawan Islands Diving - 6 Days', 'derawan-diving-6-days', 'Dive with whale sharks, turtles, and jellyfish in the crystal clear waters of Derawan Islands.', '6-day diving with whale sharks', 14500000, 'IDR', 6, 'days', 'Diving', 'Derawan', 'Flights, Resort, All Meals, Diving Equipment, Boat', 'Certification, Dive Computer, Tips', 'Whale Sharks, Jellyfish Lake, Turtle Nesting, Manta Rays', 'Weekly departures', 10, 'Moderate', 1, 'published', 112, 18, datetime('now'), datetime('now')),

('pkg-018', 'Tanjung Puting Orangutan - 4 Days', 'tanjung-puting-orangutan', 'Cruise Sekonyer River on traditional klotok boat to see wild orangutans at feeding platforms.', '4-day orangutan wildlife tour', 8500000, 'IDR', 4, 'days', 'Wildlife', 'Central Kalimantan', 'Flights, Klotok Boat, All Meals, Guide, Park Permits', 'Tips, Drinks, Personal Expenses', 'Wild Orangutans, Klotok Boat, Night Safari, Proboscis Monkeys', 'Daily departures', 12, 'Moderate', 1, 'published', 198, 32, datetime('now'), datetime('now')),

('pkg-019', 'Wakatobi Diving Paradise - 7 Days', 'wakatobi-diving-paradise', 'Dive in one of the best coral reefs in the world with incredible marine biodiversity.', '7-day diving in pristine reefs', 22000000, 'IDR', 7, 'days', 'Diving', 'Wakatobi', 'Flights, Resort, All Meals, Unlimited Diving, Equipment', 'Nitrox, Tips, Equipment Purchase', 'World Class Reefs, 50+ Dive Sites, Macro Photography, Wall Diving', 'Weekly departures', 10, 'Moderate', 1, 'published', 76, 11, datetime('now'), datetime('now')),

('pkg-020', 'Bintan Beach Resort - 3 Days', 'bintan-beach-resort', 'Quick beach getaway to Bintan with luxury resort stay, water sports, and spa treatment.', '3-day luxury beach getaway', 4800000, 'IDR', 3, 'days', 'Beach', 'Bintan', 'Ferry, Resort, Breakfast, Welcome Drink, Pool Access', 'Meals, Water Sports, Spa Treatments', 'Private Beach, Water Sports, Spa Treatment, Golf Option', 'Daily departures', 20, 'Easy', 0, 'published', 267, 54, datetime('now'), datetime('now'));
