-- Seed 20 Dummy Travel Packages for BestTravel
-- Run this with: sqlite3 besttravel.db < seed_packages.sql

-- Delete existing packages (optional - comment out if you want to keep existing data)
-- DELETE FROM packages;

-- Insert 20 dummy packages
INSERT INTO packages (id, title, slug, description, short_description, destination, price, currency, duration, max_participants, categories, images, highlights, itinerary, included, excluded, status, view_count, inquiry_count, created_at, updated_at) VALUES

-- 1. Bali Paradise
('pkg-001', 'Bali Paradise - 5 Days Cultural Experience', 'bali-paradise-5-days', 
'Discover the magic of Bali with our comprehensive 5-day cultural tour. Visit ancient temples, pristine beaches, and traditional villages. Experience authentic Balinese culture, witness stunning sunsets, and create unforgettable memories in this island paradise.',
'5-day cultural tour exploring temples, beaches, and traditional villages in Bali',
'Bali, Indonesia',
7500000, 'IDR', '5 days 4 nights', 15,
'["Beach", "Culture", "Adventure"]',
'[{"url":"/uploads/packages/bali-1.jpg","isCover":true},{"url":"/uploads/packages/bali-2.jpg","isCover":false}]',
'["Tanah Lot Temple sunset", "Ubud Monkey Forest", "Tegallalang Rice Terraces", "Traditional Balinese dance", "Seminyak Beach", "Local market shopping"]',
'[{"day":1,"title":"Arrival & Seminyak","activities":["Airport pickup","Check-in hotel","Seminyak beach sunset"],"meals":"Dinner","accommodation":"4-star hotel"},{"day":2,"title":"Ubud Culture","activities":["Ubud Monkey Forest","Tegallalang Rice Terraces","Traditional lunch","Art market"],"meals":"Breakfast, Lunch, Dinner"},{"day":3,"title":"Temple Tour","activities":["Tanah Lot Temple","Uluwatu Temple","Kecak Dance performance"],"meals":"Breakfast, Dinner"}]',
'["Airport transfers", "4-star accommodation", "Daily breakfast", "Professional guide", "All entrance tickets", "Traditional dance show"]',
'["International flights", "Personal expenses", "Travel insurance", "Lunch on day 1 & 4", "Optional activities"]',
'published', 156, 23, datetime('now'), datetime('now')),

-- 2. Raja Ampat Diving
('pkg-002', 'Raja Ampat Diving Adventure - 7 Days', 'raja-ampat-diving-7-days',
'Experience world-class diving in Raja Ampat, one of the most biodiverse marine areas on Earth. Explore pristine coral reefs, encounter manta rays, and discover hidden lagoons in this remote paradise.',
'7-day diving expedition in the stunning waters of Raja Ampat',
'Raja Ampat, West Papua',
25000000, 'IDR', '7 days 6 nights', 10,
'["Diving", "Adventure", "Nature"]',
'[{"url":"/uploads/packages/rajaampat-1.jpg","isCover":true},{"url":"/uploads/packages/rajaampat-2.jpg","isCover":false}]',
'["10+ dive sites", "Manta ray encounters", "Pristine coral reefs", "Island hopping", "Piaynemo viewpoint", "Local village visit"]',
'[{"day":1,"title":"Arrival Sorong","activities":["Fly to Sorong","Transfer to resort","Orientation dive"],"meals":"Dinner"},{"day":2,"title":"Diving Day 1","activities":["3 dives at different sites","Manta point","Night dive"],"meals":"All meals"},{"day":3,"title":"Diving Day 2","activities":["Cape Kri dive","Sardine reef","Coral garden"],"meals":"All meals"}]',
'["Domestic flights", "Liveaboard accommodation", "All meals", "10+ dives with equipment", "Dive guide", "Marine park fees"]',
'["International flights", "Diving certification", "Nitrox fills", "Alcohol beverages", "Tips for crew"]',
'published', 89, 12, datetime('now'), datetime('now')),

-- 3. Komodo Island Trek
('pkg-003', 'Komodo Island Trekking & Snorkeling', 'komodo-island-trekking',
'Trek through Komodo National Park to see the legendary Komodo dragons in their natural habitat. Snorkel in crystal-clear waters, relax on pink beaches, and witness stunning sunsets.',
'3-day adventure to see Komodo dragons and snorkel in pristine waters',
'Labuan Bajo, Flores',
4500000, 'IDR', '3 days 2 nights', 12,
'["Adventure", "Wildlife", "Snorkeling"]',
'[{"url":"/uploads/packages/komodo-1.jpg","isCover":true},{"url":"/uploads/packages/komodo-2.jpg","isCover":false}]',
'["Komodo dragon trekking", "Pink Beach", "Manta Point snorkeling", "Padar Island viewpoint", "Sunset at sea", "BBQ on boat"]',
'[{"day":1,"title":"Sail to Komodo","activities":["Depart Labuan Bajo","Snorkeling stop","Pink Beach","Overnight on boat"],"meals":"Lunch, Dinner"},{"day":2,"title":"Komodo Trek","activities":["Komodo Island trek","See dragons","Manta Point snorkeling","Padar Island hike"],"meals":"All meals"}]',
'["Boat charter", "All meals on board", "Snorkeling equipment", "Park entrance fees", "Professional guide", "Life jackets"]',
'["Hotel in Labuan Bajo", "Flights", "Personal expenses", "Drinks", "Underwater camera rental"]',
'published', 234, 45, datetime('now'), datetime('now')),

-- 4. Mount Bromo Sunrise
('pkg-004', 'Mount Bromo Sunrise Tour - 2 Days', 'mount-bromo-sunrise-tour',
'Witness the breathtaking sunrise over Mount Bromo, one of Indonesia''s most iconic volcanoes. Experience the otherworldly landscape of the Tengger caldera and explore the Sea of Sand.',
'2-day tour featuring the spectacular Mount Bromo sunrise',
'Bromo, East Java',
2500000, 'IDR', '2 days 1 night', 20,
'["Mountain", "Photography", "Adventure"]',
'[{"url":"/uploads/packages/bromo-1.jpg","isCover":true},{"url":"/uploads/packages/bromo-2.jpg","isCover":false}]',
'["Sunrise viewpoint", "Jeep adventure", "Sea of Sand", "Bromo crater", "Savanna hills", "Traditional breakfast"]',
'[{"day":1,"title":"Travel to Bromo","activities":["Pickup from Surabaya","Drive to Cemoro Lawang","Check-in hotel","Sunset walk"],"meals":"Dinner"},{"day":2,"title":"Sunrise & Return","activities":["3 AM departure","Sunrise at viewpoint","Jeep to crater","Breakfast","Return to Surabaya"],"meals":"Breakfast"}]',
'["Private car/jeep", "Hotel accommodation", "Breakfast", "Entrance fees", "Professional driver", "Flashlight"]',
'["Lunch and dinner day 1", "Personal expenses", "Horse riding (optional)", "Tips"]',
'published', 312, 67, datetime('now'), datetime('now')),

-- 5. Yogyakarta Heritage
('pkg-005', 'Yogyakarta Heritage & Temple Tour', 'yogyakarta-heritage-temple',
'Explore the cultural heart of Java with visits to magnificent Borobudur and Prambanan temples. Discover the royal palace, traditional crafts, and authentic Javanese cuisine.',
'3-day cultural journey through Yogyakarta's UNESCO World Heritage sites',
'Yogyakarta, Java',
3800000, 'IDR', '3 days 2 nights', 15,
'["Culture", "History", "Photography"]',
'[{"url":"/uploads/packages/yogya-1.jpg","isCover":true},{"url":"/uploads/packages/yogya-2.jpg","isCover":false}]',
'["Borobudur Temple sunrise", "Prambanan Temple", "Kraton Palace", "Water Castle", "Malioboro shopping", "Batik workshop"]',
'[{"day":1,"title":"Arrival & City Tour","activities":["Airport pickup","Kraton Palace","Water Castle","Malioboro street"],"meals":"Lunch, Dinner"},{"day":2,"title":"Borobudur & Prambanan","activities":["Borobudur sunrise","Village cycling","Prambanan sunset","Ramayana ballet"],"meals":"All meals"}]',
'["Airport transfers", "Hotel 3-star", "Daily breakfast", "Temple entrance fees", "English guide", "Ramayana performance"]',
'["International flights", "Lunches", "Personal expenses", "Tips"]',
'published', 198, 34, datetime('now'), datetime('now')),

-- 6. Lombok Beach Paradise
('pkg-006', 'Lombok Beach Paradise - 4 Days', 'lombok-beach-paradise',
'Relax on pristine white-sand beaches, surf world-class waves, and explore traditional Sasak villages. Lombok offers the perfect blend of adventure and relaxation.',
'4-day beach getaway in beautiful Lombok',
'Lombok, West Nusa Tenggara',
5200000, 'IDR', '4 days 3 nights', 12,
'["Beach", "Surfing", "Relaxation"]',
'[{"url":"/uploads/packages/lombok-1.jpg","isCover":true},{"url":"/uploads/packages/lombok-2.jpg","isCover":false}]',
'["Kuta Beach surfing", "Pink Beach", "Tanjung Aan", "Traditional village", "Waterfall trek", "Sunset cruise"]',
'[{"day":1,"title":"Arrival & South Coast","activities":["Airport transfer","Kuta Beach","Surfing lesson","Sunset dinner"],"meals":"Dinner"},{"day":2,"title":"Island Hopping","activities":["Boat to Gili islands","Snorkeling","Beach time","Return to Lombok"],"meals":"Breakfast, Lunch"}]',
'["Airport transfers", "Beachfront hotel", "Breakfast daily", "Surfing lesson", "Snorkeling equipment", "Boat trips"]',
'["Flights", "Lunches & dinners", "Surfboard rental", "Personal expenses"]',
'published', 145, 28, datetime('now'), datetime('now')),

-- 7. Sumatra Wildlife Safari
('pkg-007', 'Sumatra Wildlife Safari - 5 Days', 'sumatra-wildlife-safari',
'Trek through Gunung Leuser National Park to see orangutans, elephants, and tigers in their natural habitat. Experience authentic jungle camping and river rafting.',
'5-day wildlife adventure in Sumatra's pristine rainforest',
'Medan, North Sumatra',
12000000, 'IDR', '5 days 4 nights', 8,
'["Wildlife", "Jungle", "Adventure"]',
'[{"url":"/uploads/packages/sumatra-1.jpg","isCover":true},{"url":"/uploads/packages/sumatra-2.jpg","isCover":false}]',
'["Orangutan spotting", "Jungle trekking", "River rafting", "Elephant sanctuary", "Camping in jungle", "Hot springs"]',
'[{"day":1,"title":"Medan to Bukit Lawang","activities":["Pickup from Medan","Drive to Bukit Lawang","Village tour","River tubing"],"meals":"Lunch, Dinner"},{"day":2,"title":"Jungle Trek Day 1","activities":["Early morning trek","Orangutan tracking","River crossing","Jungle camp"],"meals":"All meals"}]',
'["Medan transfers", "Jungle camping", "All meals", "Professional guide", "Trekking permits", "Camping equipment"]',
'["Flights to Medan", "Hotel night 1", "Personal expenses", "Tips for guide"]',
'published', 76, 15, datetime('now'), datetime('now')),

-- 8. Gili Islands Escape
('pkg-008', 'Gili Islands Escape - 3 Days', 'gili-islands-escape',
'Discover the laid-back charm of Gili Islands. Snorkel with turtles, cycle around the islands, and enjoy stunning sunsets on these car-free tropical paradises.',
'3-day island escape to the beautiful Gili Islands',
'Gili Trawangan, Lombok',
3500000, 'IDR', '3 days 2 nights', 16,
'["Beach", "Snorkeling", "Island"]',
'[{"url":"/uploads/packages/gili-1.jpg","isCover":true},{"url":"/uploads/packages/gili-2.jpg","isCover":false}]',
'["Turtle snorkeling", "Island hopping", "Bicycle tour", "Sunset swing", "Beach parties", "Fresh seafood"]',
'[{"day":1,"title":"Arrival Gili T","activities":["Fast boat transfer","Check-in hotel","Snorkeling trip","Sunset viewing"],"meals":"Dinner"},{"day":2,"title":"3 Islands Tour","activities":["Visit Gili Meno","Gili Air exploration","Underwater statues","BBQ lunch"],"meals":"Breakfast, Lunch"}]',
'["Fast boat transfers", "Beach hotel", "Breakfast", "Snorkeling equipment", "Island hopping boat", "Bicycle rental"]',
'["Lunches & dinners", "Diving courses", "Scooter rental", "Party expenses"]',
'published', 267, 52, datetime('now'), datetime('now')),

-- 9. Sulawesi Cultural Tour
('pkg-009', 'Toraja Cultural Experience - 6 Days', 'toraja-cultural-experience',
'Immerse yourself in the fascinating Toraja culture of South Sulawesi. Visit ancient burial sites, traditional villages, and witness unique funeral ceremonies.',
'6-day cultural journey through mystical Toraja highlands',
'Makassar, South Sulawesi',
9500000, 'IDR', '6 days 5 nights', 10,
'["Culture", "Adventure", "Photography"]',
'[{"url":"/uploads/packages/toraja-1.jpg","isCover":true},{"url":"/uploads/packages/toraja-2.jpg","isCover":false}]',
'["Traditional villages", "Tongkonan houses", "Rock graves", "Hanging graves", "Local ceremonies", "Coffee plantations"]',
'[{"day":1,"title":"Makassar to Toraja","activities":["Fly to Makassar","Drive to Toraja","Scenic mountain road","Local dinner"],"meals":"Lunch, Dinner"},{"day":2,"title":"Toraja Exploration","activities":["Lemo cliff graves","Kete Kesu village","Traditional houses","Weaving demo"],"meals":"All meals"}]',
'["Domestic flights", "Hotel accommodation", "All meals", "Private car", "English guide", "Entrance fees"]',
'["International flights", "Personal expenses", "Tips", "Additional activities"]',
'published', 54, 9, datetime('now'), datetime('now')),

-- 10. Banda Islands Expedition
('pkg-010', 'Banda Islands Historical Tour', 'banda-islands-historical',
'Explore the legendary Spice Islands, where nutmeg changed world history. Snorkel pristine reefs, visit Dutch colonial forts, and enjoy fresh seafood.',
'4-day expedition to the historic Banda Islands',
'Banda Neira, Maluku',
15000000, 'IDR', '4 days 3 nights', 8,
'["History", "Snorkeling", "Island"]',
'[{"url":"/uploads/packages/banda-1.jpg","isCover":true},{"url":"/uploads/packages/banda-2.jpg","isCover":false}]',
'["Fort Belgica", "Nutmeg plantations", "Snorkeling coral reefs", "Volcano trekking", "Colonial architecture", "Fresh seafood"]',
'[{"day":1,"title":"Arrival Banda","activities":["Fly to Ambon","Boat to Banda","Fort Belgica visit","Town walk"],"meals":"Lunch, Dinner"},{"day":2,"title":"Island Exploration","activities":["Boat trip","Snorkeling","Ai Island","Volcano viewpoint"],"meals":"All meals"}]',
'["Flights Ambon-Banda", "Guesthouse", "All meals", "Boat trips", "Snorkeling gear", "Guide", "Entrance fees"]',
'["Jakarta-Ambon flights", "Personal expenses", "Alcohol", "Tips"]',
'published', 42, 6, datetime('now'), datetime('now')),

-- 11. Java Coffee Trail
('pkg-011', 'Java Coffee Trail & Plantation Tour', 'java-coffee-trail',
'Journey through Java''s coffee heartland. Visit working plantations, learn about coffee processing, and taste some of the world''s finest beans in stunning highland settings.',
'3-day coffee lover's tour through Java plantations',
'Bandung & Garut, West Java',
4200000, 'IDR', '3 days 2 nights', 12,
'["Culinary", "Nature", "Culture"]',
'[{"url":"/uploads/packages/coffee-1.jpg","isCover":true},{"url":"/uploads/packages/coffee-2.jpg","isCover":false}]',
'["Coffee plantation tours", "Roasting workshops", "Cupping sessions", "Tea gardens", "Volcanic crater lake", "Local cuisine"]',
'[{"day":1,"title":"Bandung Highlands","activities":["Pickup Jakarta","Drive to Bandung","Coffee plantation tour","Roasting demo"],"meals":"Lunch, Dinner"},{"day":2,"title":"Garut Coffee Trail","activities":["Plantation trekking","Coffee processing","Cupping session","Crater lake visit"],"meals":"All meals"}]',
'["Private car", "Plantation hotel", "All meals", "Coffee tastings", "Plantation tours", "Guide"]',
'["Personal purchases", "Coffee souvenirs", "Tips"]',
'published', 87, 16, datetime('now'), datetime('now')),

-- 12. Nias Island Surfing
('pkg-012', 'Nias Island Surf Camp - 7 Days', 'nias-island-surf-camp',
'Ride legendary waves at Nias Island, one of Indonesia''s best surf destinations. Perfect for intermediate to advanced surfers seeking consistent swells and uncrowded breaks.',
'7-day surf camp on the legendary waves of Nias',
'Nias Island, North Sumatra',
8500000, 'IDR', '7 days 6 nights', 10,
'["Surfing", "Beach", "Adventure"]',
'[{"url":"/uploads/packages/nias-1.jpg","isCover":true},{"url":"/uploads/packages/nias-2.jpg","isCover":false}]',
'["Lagundri Bay waves", "Multiple surf spots", "Surf coaching", "Board rental", "Traditional village", "Sunset sessions"]',
'[{"day":1,"title":"Arrival & Orientation","activities":["Airport transfer","Beach check","Equipment setup","Sunset surf"],"meals":"Dinner"},{"day":2,"title":"Surf Day 1","activities":["Morning session","Video analysis","Afternoon surf","Theory class"],"meals":"All meals"}]',
'["Airport transfers", "Beachfront lodge", "All meals", "Surf coaching", "Board rental", "Video analysis"]',
'["Flights to Nias", "Wetsuit rental", "Surf photos", "Personal expenses"]',
'published', 112, 21, datetime('now'), datetime('now')),

-- 13. Thousand Islands Getaway
('pkg-013', 'Thousand Islands Weekend Escape', 'thousand-islands-escape',
'Quick escape from Jakarta to pristine islands. Snorkel in clear waters, relax on white beaches, and enjoy fresh seafood just hours from the city.',
'2-day island getaway from Jakarta',
'Pulau Seribu, Jakarta',
2800000, 'IDR', '2 days 1 night', 20,
'["Beach", "Snorkeling", "Relaxation"]',
'[{"url":"/uploads/packages/seribu-1.jpg","isCover":true},{"url":"/uploads/packages/seribu-2.jpg","isCover":false}]',
'["Island hopping", "Coral reef snorkeling", "Beach relaxation", "Seafood dinner", "Sunset viewing", "Water sports"]',
'[{"day":1,"title":"Island Adventure","activities":["Marina pickup","Fast boat","Snorkeling 3 spots","Beach time","Sunset BBQ"],"meals":"Lunch, Dinner"},{"day":2,"title":"Leisure & Return","activities":["Free time","Water activities","Late checkout","Return Jakarta"],"meals":"Breakfast, Lunch"}]',
'["Marina transfers", "Fast boat", "Island resort", "All meals", "Snorkeling equipment", "Life jackets"]',
'["Jakarta transfers", "Water sports", "Drinks", "Tips"]',
'published', 289, 58, datetime('now'), datetime('now')),

-- 14. Belitung Island
('pkg-014', 'Belitung Island Beach Hopping', 'belitung-island-hopping',
'Discover Belitung''s unique granite rock formations and crystal-clear waters. Hop between stunning beaches and islands with emerald seas and white sand.',
'3-day island hopping adventure in Belitung',
'Belitung Island',
5800000, 'IDR', '3 days 2 nights', 12,
'["Beach", "Island", "Photography"]',
'[{"url":"/uploads/packages/belitung-1.jpg","isCover":true},{"url":"/uploads/packages/belitung-2.jpg","isCover":false}]',
'["Tanjung Tinggi Beach", "Lengkuas lighthouse", "Island hopping", "Granite formations", "Snorkeling", "Local seafood"]',
'[{"day":1,"title":"West Coast Tour","activities":["Airport pickup","Tanjung Tinggi","Tanjung Kelayang","Sunset at beach"],"meals":"Lunch, Dinner"},{"day":2,"title":"Island Hopping","activities":["Boat trip","5 islands visit","Lengkuas Island","Snorkeling stops"],"meals":"All meals"}]',
'["Airport transfers", "Beach hotel", "All meals", "Boat charter", "Snorkeling gear", "Island fees"]',
'["Flights", "Personal expenses", "Drinks", "Water activities"]',
'published', 167, 32, datetime('now'), datetime('now')),

-- 15. Papua Adventure
('pkg-015', 'Papua Tribal & Nature Expedition', 'papua-tribal-expedition',
'Experience authentic Papua tribal culture and pristine nature. Trek through rainforests, meet indigenous tribes, and witness unique traditions in Indonesia''s final frontier.',
'8-day expedition into Papua's tribal heartland',
'Wamena, Papua',
28000000, 'IDR', '8 days 7 nights', 6,
'["Culture", "Adventure", "Trekking"]',
'[{"url":"/uploads/packages/papua-1.jpg","isCover":true},{"url":"/uploads/packages/papua-2.jpg","isCover":false}]',
'["Dani tribe visit", "Tribal ceremonies", "Valley trekking", "Traditional villages", "Mummy caves", "Salt springs"]',
'[{"day":1,"title":"Arrival Wamena","activities":["Fly to Wamena","Hotel check-in","Market visit","Cultural orientation"],"meals":"Lunch, Dinner"},{"day":2,"title":"Valley Trek","activities":["Trek to villages","Meet Dani people","Traditional cooking","Overnight in honai"],"meals":"All meals"}]',
'["Domestic flights", "Accommodation", "All meals", "Trekking guide", "Porter services", "Cultural permits", "Traditional gifts"]',
'["Jakarta-Papua flights", "Personal gear", "Tips", "Extra snacks"]',
'draft', 31, 4, datetime('now'), datetime('now')),

-- 16. Malang Mountain Tour
('pkg-016', 'Malang Mountain & Waterfall Tour', 'malang-mountain-waterfall',
'Explore East Java''s cool mountain town of Malang. Visit colorful flower gardens, stunning waterfalls, and charming colonial architecture.',
'3-day mountain retreat in beautiful Malang',
'Malang, East Java',
3200000, 'IDR', '3 days 2 nights', 15,
'["Mountain", "Nature", "Photography"]',
'[{"url":"/uploads/packages/malang-1.jpg","isCover":true},{"url":"/uploads/packages/malang-2.jpg","isCover":false}]',
'["Coban Rondo waterfall", "Flower gardens", "Rainbow village", "Apple orchards", "Colonial buildings", "Local coffee"]',
'[{"day":1,"title":"City Tour","activities":["Pickup Surabaya","Drive to Malang","City tour","Colonial district"],"meals":"Lunch, Dinner"},{"day":2,"title":"Mountain Exploration","activities":["Coban Rondo","Selecta park","Village tour","Sunset viewpoint"],"meals":"All meals"}]',
'["Private car", "Hotel 3-star", "Breakfast daily", "Entrance fees", "Driver", "Fuel"]',
'["Lunches & dinners", "Personal expenses", "Tips"]',
'published', 178, 29, datetime('now'), datetime('now')),

-- 17. Derawan Islands
('pkg-017', 'Derawan Islands Marine Paradise', 'derawan-islands-marine',
'Swim with stingless jellyfish, encounter sea turtles, and explore untouched beaches in East Kalimantan''s hidden paradise.',
'4-day marine adventure in Derawan archipelago',
'Derawan, East Kalimantan',
11000000, 'IDR', '4 days 3 nights', 10,
'["Snorkeling", "Island", "Wildlife"]',
'[{"url":"/uploads/packages/derawan-1.jpg","isCover":true},{"url":"/uploads/packages/derawan-2.jpg","isCover":false}]',
'["Kakaban jellyfish lake", "Turtle nesting sites", "Maratua atoll", "Manta ray point", "Pristine beaches", "Night snorkeling"]',
'[{"day":1,"title":"Arrival Derawan","activities":["Fly to Berau","Boat to Derawan","Check-in","Turtle spotting"],"meals":"Lunch, Dinner"},{"day":2,"title":"Island Hopping","activities":["Kakaban Island","Jellyfish lake","Maratua visit","Snorkeling"],"meals":"All meals"}]',
'["Flights & boats", "Beach resort", "All meals", "Island hopping", "Snorkeling equipment", "Guide", "Park fees"]',
'["Jakarta flights", "Diving equipment", "Personal expenses", "Tips"]',
'published', 93, 17, datetime('now'), datetime('now')),

-- 18. Tanjung Puting Safari
('pkg-018', 'Tanjung Puting Orangutan Safari', 'tanjung-puting-orangutan',
'Cruise through Borneo''s rivers to see orangutans at feeding stations. Sleep on a traditional klotok boat and experience jungle nights.',
'4-day orangutan safari on traditional boat',
'Pangkalan Bun, Kalimantan',
9800000, 'IDR', '4 days 3 nights', 8,
'["Wildlife", "Jungle", "River"]',
'[{"url":"/uploads/packages/tanjung-1.jpg","isCover":true},{"url":"/uploads/packages/tanjung-2.jpg","isCover":false}]',
'["Wild orangutans", "Klotok river cruise", "Feeding platforms", "Proboscis monkeys", "Night jungle sounds", "River fishing"]',
'[{"day":1,"title":"Begin Safari","activities":["Airport transfer","Board klotok","River cruise","Camp Leakey visit"],"meals":"Lunch, Dinner"},{"day":2,"title":"Deep Jungle","activities":["Early orangutan tracking","Pondok Tanggui","Forest trek","River wildlife"],"meals":"All meals"}]',
'["Airport transfers", "Klotok boat", "All meals", "Park permits", "Guide", "Bedding on boat"]',
'["Flights", "Hotel before/after", "Tips", "Snacks"]',
'published', 68, 13, datetime('now'), datetime('now')),

-- 19. Wakatobi Diving
('pkg-019', 'Wakatobi Diving Paradise - 6 Days', 'wakatobi-diving-paradise',
'Dive one of the world''s most pristine reef systems in Southeast Sulawesi. Experience incredible marine biodiversity and untouched coral gardens.',
'6-day diving expedition in Wakatobi',
'Wakatobi, Southeast Sulawesi',
22000000, 'IDR', '6 days 5 nights', 8,
'["Diving", "Marine", "Adventure"]',
'[{"url":"/uploads/packages/wakatobi-1.jpg","isCover":true},{"url":"/uploads/packages/wakatobi-2.jpg","isCover":false}]',
'["House reef diving", "Wall dives", "Drift dives", "Macro photography", "Coral gardens", "Turtle encounters"]',
'[{"day":1,"title":"Arrival","activities":["Fly to Wakatobi","Resort check-in","Orientation dive","Equipment setup"],"meals":"Dinner"},{"day":2,"title":"Diving Day 1","activities":["3 boat dives","Various sites","Night dive","Log dive"],"meals":"All meals"}]',
'["Domestic flights", "Dive resort", "All meals", "12+ dives", "Equipment", "Nitrox", "Park fees", "Transfers"]',
'["International flights", "Alcohol", "Dive courses", "Tips"]',
'published', 81, 14, datetime('now'), datetime('now')),

-- 20. Bintan Beach Resort
('pkg-020', 'Bintan Beach Resort Getaway', 'bintan-beach-resort',
'Quick tropical escape to Bintan Island. Enjoy luxury resorts, pristine beaches, and water sports just a ferry ride from Singapore.',
'3-day beach resort vacation in Bintan',
'Bintan Island, Riau Islands',
4800000, 'IDR', '3 days 2 nights', 20,
'["Beach", "Relaxation", "Resort"]',
'[{"url":"/uploads/packages/bintan-1.jpg","isCover":true},{"url":"/uploads/packages/bintan-2.jpg","isCover":false}]',
'["Beach resort", "Water sports", "Spa treatments", "Mangrove tour", "Seafood dining", "Sunset cruise"]',
'[{"day":1,"title":"Arrival & Relax","activities":["Ferry from Singapore/Jakarta","Resort check-in","Beach time","Welcome dinner"],"meals":"Dinner"},{"day":2,"title":"Water Activities","activities":["Kayaking","Stand-up paddle","Snorkeling","Spa session"],"meals":"Breakfast"}]',
'["Ferry transfers", "4-star resort", "Daily breakfast", "Welcome dinner", "Basic water sports", "Resort facilities"]',
'["Lunches & dinners", "Spa treatments", "Motorized water sports", "Tips"]',
'published', 245, 48, datetime('now'), datetime('now'));

-- Verify insertion
SELECT COUNT(*) as total_packages FROM packages;
SELECT title, price, status FROM packages ORDER BY created_at DESC LIMIT 5;
