-- Simple seed for 20 travel packages
-- Compatible with SQLite and PowerShell

INSERT INTO packages (id, title, slug, description, destination, price, currency, duration, categories, images, highlights, itinerary, included, excluded, status, created_at, updated_at) VALUES
('pkg-001', 'Bali Paradise - 5 Days', 'bali-paradise-5-days', 'Experience authentic Balinese culture with temple visits, beach relaxation, and traditional villages.', 'Bali', 7500000, 'IDR', '5 days 4 nights', '["Beach","Culture"]', '[{"url":"/uploads/bali.jpg","isCover":true}]', '["Tanah Lot Temple","Ubud Rice Terraces","Traditional Dance"]', '[]', 'Accommodation, Breakfast, Guide, Tickets', 'Flights, Lunch, Dinner', 'published', datetime('now'), datetime('now')),
('pkg-002', 'Raja Ampat Diving - 7 Days', 'raja-ampat-diving-7-days', 'World-class diving in the most biodiverse marine area. See manta rays and pristine coral reefs.', 'Raja Ampat', 25000000, 'IDR', '7 days 6 nights', '["Diving","Adventure"]', '[{"url":"/uploads/rajaampat.jpg","isCover":true}]', '["10+ Dive Sites","Manta Rays","Coral Reefs"]', '[]', 'Flights, Accommodation, Meals, Equipment', 'Certification, Nitrox, Tips', 'published', datetime('now'), datetime('now')),
('pkg-003', 'Komodo Island Trek - 3 Days', 'komodo-island-trekking', 'Trek to see legendary Komodo dragons, snorkel at Pink Beach, and explore Padar Island.', 'Labuan Bajo', 4500000, 'IDR', '3 days 2 nights', '["Adventure","Wildlife"]', '[{"url":"/uploads/komodo.jpg","isCover":true}]', '["Komodo Dragons","Pink Beach","Manta Point"]', '[]', 'Boat, Meals, Equipment, Guide', 'Hotel, Flights, Drinks', 'published', datetime('now'), datetime('now')),
('pkg-004', 'Bromo Sunrise Tour - 2 Days', 'bromo-sunrise-tour', 'Witness magical sunrise at Mount Bromo, explore the volcanic crater, and visit local villages.', 'Malang', 2500000, 'IDR', '2 days 1 night', '["Mountain","Adventure"]', '[{"url":"/uploads/bromo.jpg","isCover":true}]', '["Sunrise Viewpoint","Crater Trek","Jeep Safari"]', '[]', 'Transport, Hotel, Breakfast, Guide', 'Lunch, Dinner, Horse Rental', 'published', datetime('now'), datetime('now')),
('pkg-005', 'Yogyakarta Heritage - 4 Days', 'yogyakarta-heritage-4-days', 'Explore ancient temples of Borobudur and Prambanan, learn batik making, and visit Kraton palace.', 'Yogyakarta', 3800000, 'IDR', '4 days 3 nights', '["Culture","Heritage"]', '[{"url":"/uploads/jogja.jpg","isCover":true}]', '["Borobudur Temple","Prambanan","Batik Workshop"]', '[]', 'Hotel, Breakfast, Transport, Tickets', 'Flights, Lunch, Dinner', 'published', datetime('now'), datetime('now')),
('pkg-006', 'Lombok Beach Escape - 5 Days', 'lombok-beach-escape', 'Relax on pristine beaches, hike Rinjani base, and explore waterfalls in peaceful Lombok.', 'Lombok', 5200000, 'IDR', '5 days 4 nights', '["Beach","Relaxation"]', '[{"url":"/uploads/lombok.jpg","isCover":true}]', '["Senggigi Beach","Tiu Kelep Waterfall","Gili Islands"]', '[]', 'Hotel, Breakfast, Transport, Boat', 'Flights, Meals, Activities', 'published', datetime('now'), datetime('now')),
('pkg-007', 'Lake Toba Highland - 4 Days', 'lake-toba-highland', 'Discover the beauty of Lake Toba, visit Batak villages, and enjoy cool mountain air.', 'North Sumatra', 4200000, 'IDR', '4 days 3 nights', '["Nature","Culture"]', '[{"url":"/uploads/toba.jpg","isCover":true}]', '["Lake Toba Cruise","Samosir Island","Batak Traditional Houses"]', '[]', 'Hotel, Breakfast, Ferry, Guide', 'Flights, Lunch, Dinner', 'published', datetime('now'), datetime('now')),
('pkg-008', 'Gili Islands Hopping - 3 Days', 'gili-islands-hopping', 'Explore three paradise islands: Gili Trawangan, Gili Meno, and Gili Air with snorkeling.', 'Gili Islands', 3500000, 'IDR', '3 days 2 nights', '["Beach","Snorkeling"]', '[{"url":"/uploads/gili.jpg","isCover":true}]', '["Island Hopping","Turtle Snorkeling","Beach Party"]', '[]', 'Hotel, Breakfast, Boat, Equipment', 'Flights, Lunch, Dinner', 'published', datetime('now'), datetime('now')),
('pkg-009', 'Toraja Funeral Ceremony - 5 Days', 'toraja-funeral-ceremony', 'Witness unique Torajan culture and funeral ceremonies in the highlands of Sulawesi.', 'Tana Toraja', 6800000, 'IDR', '5 days 4 nights', '["Culture","Heritage"]', '[{"url":"/uploads/toraja.jpg","isCover":true}]', '["Funeral Ceremony","Traditional Houses","Rock Graves"]', '[]', 'Hotel, Meals, Transport, Guide', 'Flights, Ceremony Offerings', 'published', datetime('now'), datetime('now')),
('pkg-010', 'Banda Islands Spice Route - 6 Days', 'banda-islands-spice', 'Follow the historical spice trade route, dive in pristine waters, and explore colonial forts.', 'Banda Islands', 12000000, 'IDR', '6 days 5 nights', '["History","Diving"]', '[{"url":"/uploads/banda.jpg","isCover":true}]', '["Spice Plantations","Fort Belgica","Diving Sites"]', '[]', 'Flights, Hotel, Meals, Diving', 'Personal Expenses, Tips', 'published', datetime('now'), datetime('now')),
('pkg-011', 'Java Coffee Trail - 4 Days', 'java-coffee-trail', 'Journey through Java coffee plantations, learn roasting process, and taste premium beans.', 'Central Java', 3200000, 'IDR', '4 days 3 nights', '["Culture","Food"]', '[{"url":"/uploads/coffee.jpg","isCover":true}]', '["Coffee Plantation Tour","Roasting Workshop","Tasting Sessions"]', '[]', 'Hotel, Breakfast, Tours, Samples', 'Flights, Lunch, Dinner', 'published', datetime('now'), datetime('now')),
('pkg-012', 'Nias Island Surfing - 5 Days', 'nias-island-surfing', 'Catch world-class waves at Lagundri Bay and experience traditional stone jumping.', 'Nias Island', 5800000, 'IDR', '5 days 4 nights', '["Surfing","Adventure"]', '[{"url":"/uploads/nias.jpg","isCover":true}]', '["Lagundri Bay Surf","Stone Jumping","Traditional Villages"]', '[]', 'Hotel, Breakfast, Boat, Guide', 'Flights, Surfboard Rental, Meals', 'published', datetime('now'), datetime('now')),
('pkg-013', 'Thousand Islands Snorkeling - 2 Days', 'thousand-islands-snorkeling', 'Quick getaway from Jakarta to pristine islands with excellent snorkeling and beach time.', 'Thousand Islands', 2800000, 'IDR', '2 days 1 night', '["Beach","Snorkeling"]', '[{"url":"/uploads/pulauseribu.jpg","isCover":true}]', '["Coral Snorkeling","Island Hopping","Beach BBQ"]', '[]', 'Boat, Hotel, Meals, Equipment', 'Transport to Marina', 'published', datetime('now'), datetime('now')),
('pkg-014', 'Belitung Island Granite - 4 Days', 'belitung-granite-beaches', 'Explore stunning granite rock formations and pristine beaches made famous by Indonesian films.', 'Belitung', 4800000, 'IDR', '4 days 3 nights', '["Beach","Photography"]', '[{"url":"/uploads/belitung.jpg","isCover":true}]', '["Tanjung Tinggi Beach","Island Hopping","Granite Rocks"]', '[]', 'Hotel, Breakfast, Boat, Guide', 'Flights, Lunch, Dinner', 'published', datetime('now'), datetime('now')),
('pkg-015', 'Papua Tribal Expedition - 8 Days', 'papua-tribal-expedition', 'Deep expedition into Papua highlands to meet Dani tribe and experience ancient culture.', 'Wamena', 28000000, 'IDR', '8 days 7 nights', '["Culture","Adventure"]', '[{"url":"/uploads/papua.jpg","isCover":true}]', '["Dani Tribe Visit","Baliem Valley","Traditional Ceremonies"]', '[]', 'Flights, Accommodation, Meals, Guide, Permits', 'Personal Gear, Tips, Offerings', 'draft', datetime('now'), datetime('now')),
('pkg-016', 'Malang City & Beaches - 3 Days', 'malang-city-beaches', 'Explore colorful Malang city, visit Apple orchards, and relax at southern beaches.', 'Malang', 3100000, 'IDR', '3 days 2 nights', '["City","Beach"]', '[{"url":"/uploads/malang.jpg","isCover":true}]', '["Colorful Village","Apple Picking","Beach Visit"]', '[]', 'Hotel, Breakfast, Transport, Tickets', 'Flights, Meals, Shopping', 'published', datetime('now'), datetime('now')),
('pkg-017', 'Derawan Islands Diving - 6 Days', 'derawan-diving-6-days', 'Dive with whale sharks, turtles, and jellyfish in the crystal waters of Derawan Islands.', 'Derawan', 14500000, 'IDR', '6 days 5 nights', '["Diving","Wildlife"]', '[{"url":"/uploads/derawan.jpg","isCover":true}]', '["Whale Sharks","Jellyfish Lake","Turtle Nesting"]', '[]', 'Flights, Resort, Meals, Diving Equipment', 'Certification, Dive Computer', 'published', datetime('now'), datetime('now')),
('pkg-018', 'Tanjung Puting Orangutan - 4 Days', 'tanjung-puting-orangutan', 'Cruise Sekonyer River on traditional klotok boat to see wild orangutans feeding.', 'Central Kalimantan', 8500000, 'IDR', '4 days 3 nights', '["Wildlife","Nature"]', '[{"url":"/uploads/orangutan.jpg","isCover":true}]', '["Wild Orangutans","Klotok Boat","Night Safari"]', '[]', 'Flights, Klotok, Meals, Guide, Permits', 'Tips, Drinks, Personal Expenses', 'published', datetime('now'), datetime('now')),
('pkg-019', 'Wakatobi Diving Paradise - 7 Days', 'wakatobi-diving-paradise', 'Dive in one of the best coral reefs in the world with incredible marine biodiversity.', 'Wakatobi', 22000000, 'IDR', '7 days 6 nights', '["Diving","Marine"]', '[{"url":"/uploads/wakatobi.jpg","isCover":true}]', '["World Class Reefs","50+ Dive Sites","Macro Photography"]', '[]', 'Flights, Resort, Meals, Unlimited Diving', 'Nitrox, Tips, Equipment Purchase', 'published', datetime('now'), datetime('now')),
('pkg-020', 'Bintan Beach Resort - 3 Days', 'bintan-beach-resort', 'Quick beach getaway to Bintan with luxury resort stay, water sports, and spa.', 'Bintan', 4800000, 'IDR', '3 days 2 nights', '["Beach","Relaxation"]', '[{"url":"/uploads/bintan.jpg","isCover":true}]', '["Private Beach","Water Sports","Spa Treatment"]', '[]', 'Ferry, Resort, Breakfast, Welcome Drink', 'Meals, Activities, Spa Extra', 'published', datetime('now'), datetime('now'));
