SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;
TRUNCATE TABLE itinerary_items;
TRUNCATE TABLE package_images;
TRUNCATE TABLE packages;
SET FOREIGN_KEY_CHECKS=1;

INSERT INTO packages(
  id,title,title_zh,slug,description,description_zh,short_description,short_description_zh,
  price,currency,duration,duration_unit,categories,categories_zh,destination,destination_zh,
  included,included_zh,excluded,excluded_zh,highlights,highlights_zh,availability,availability_zh,
  max_participants,featured,status,view_count,inquiry_count,created_at,updated_at
) VALUES
('pkg-demo-001','Demo Package 001','示例套餐 001','demo-package-1','Demo English description 001','中文示例描述 001','Short demo 001','简短示例 001',1005000,'IDR',3,'days','["demo","test"]','["示例","测试"]','bali','巴厘岛','["hotel","breakfast"]','["酒店","早餐"]','["flights"]','["机票"]','["highlight-a","highlight-b"]','["亮点A","亮点B"]','year-round','全年可订',25,1,'published',0,0,NOW(),NOW()),
('pkg-demo-002','Demo Package 002','示例套餐 002','demo-package-2','Demo English description 002','中文示例描述 002','Short demo 002','简短示例 002',1010000,'IDR',4,'days','["demo","test"]','["示例","测试"]','lombok','龙目岛','["hotel","breakfast"]','["酒店","早餐"]','["flights"]','["机票"]','["highlight-a","highlight-b"]','["亮点A","亮点B"]','year-round','全年可订',26,0,'published',0,0,NOW(),NOW()),
('pkg-demo-003','Demo Package 003','示例套餐 003','demo-package-3','Demo English description 003','中文示例描述 003','Short demo 003','简短示例 003',1015000,'IDR',5,'days','["demo","test"]','["示例","测试"]','yogyakarta','日惹','["hotel","breakfast"]','["酒店","早餐"]','["flights"]','["机票"]','["highlight-a","highlight-b"]','["亮点A","亮点B"]','year-round','全年可订',27,0,'published',0,0,NOW(),NOW()),
('pkg-demo-004','Demo Package 004','示例套餐 004','demo-package-4','Demo English description 004','中文示例描述 004','Short demo 004','简短示例 004',1020000,'IDR',6,'days','["demo","test"]','["示例","测试"]','komodo','科莫多','["hotel","breakfast"]','["酒店","早餐"]','["flights"]','["机票"]','["highlight-a","highlight-b"]','["亮点A","亮点B"]','year-round','全年可订',28,0,'published',0,0,NOW(),NOW()),
('pkg-demo-005','Demo Package 005','示例套餐 005','demo-package-5','Demo English description 005','中文示例描述 005','Short demo 005','简短示例 005',1025000,'IDR',7,'days','["demo","test"]','["示例","测试"]','jakarta','雅加达','["hotel","breakfast"]','["酒店","早餐"]','["flights"]','["机票"]','["highlight-a","highlight-b"]','["亮点A","亮点B"]','year-round','全年可订',29,0,'published',0,0,NOW(),NOW()),
('pkg-demo-006','Demo Package 006','示例套餐 006','demo-package-6','Demo English description 006','中文示例描述 006','Short demo 006','简短示例 006',1030000,'IDR',8,'days','["demo","test"]','["示例","测试"]','bandung','万隆','["hotel","breakfast"]','["酒店","早餐"]','["flights"]','["机票"]','["highlight-a","highlight-b"]','["亮点A","亮点B"]','year-round','全年可订',30,0,'published',0,0,NOW(),NOW()),
('pkg-demo-007','Demo Package 007','示例套餐 007','demo-package-7','Demo English description 007','中文示例描述 007','Short demo 007','简短示例 007',1035000,'IDR',9,'days','["demo","test"]','["示例","测试"]','bromo','布罗莫','["hotel","breakfast"]','["酒店","早餐"]','["flights"]','["机票"]','["highlight-a","highlight-b"]','["亮点A","亮点B"]','year-round','全年可订',31,0,'published',0,0,NOW(),NOW()),
('pkg-demo-008','Demo Package 008','示例套餐 008','demo-package-8','Demo English description 008','中文示例描述 008','Short demo 008','简短示例 008',1040000,'IDR',10,'days','["demo","test"]','["示例","测试"]','raja-ampat','四王群岛','["hotel","breakfast"]','["酒店","早餐"]','["flights"]','["机票"]','["highlight-a","highlight-b"]','["亮点A","亮点B"]','year-round','全年可订',32,0,'published',0,0,NOW(),NOW()),
('pkg-demo-009','Demo Package 009','示例套餐 009','demo-package-9','Demo English description 009','中文示例描述 009','Short demo 009','简短示例 009',1045000,'IDR',11,'days','["demo","test"]','["示例","测试"]','sumba','松巴','["hotel","breakfast"]','["酒店","早餐"]','["flights"]','["机票"]','["highlight-a","highlight-b"]','["亮点A","亮点B"]','year-round','全年可订',33,0,'published',0,0,NOW(),NOW()),
('pkg-demo-010','Demo Package 010','示例套餐 010','demo-package-10','Demo English description 010','中文示例描述 010','Short demo 010','简短示例 010',1050000,'IDR',12,'days','["demo","test"]','["示例","测试"]','belitung','勿里洞','["hotel","breakfast"]','["酒店","早餐"]','["flights"]','["机票"]','["highlight-a","highlight-b"]','["亮点A","亮点B"]','year-round','全年可订',34,0,'published',0,0,NOW(),NOW()),
('pkg-demo-011','Demo Package 011','示例套餐 011','demo-package-11','Demo English description 011','中文示例描述 011','Short demo 011','简短示例 011',1055000,'IDR',3,'days','["demo","test"]','["示例","测试"]','bali','巴厘岛','["hotel","breakfast"]','["酒店","早餐"]','["flights"]','["机票"]','["highlight-a","highlight-b"]','["亮点A","亮点B"]','year-round','全年可订',25,1,'published',0,0,NOW(),NOW()),
('pkg-demo-012','Demo Package 012','示例套餐 012','demo-package-12','Demo English description 012','中文示例描述 012','Short demo 012','简短示例 012',1060000,'IDR',4,'days','["demo","test"]','["示例","测试"]','lombok','龙目岛','["hotel","breakfast"]','["酒店","早餐"]','["flights"]','["机票"]','["highlight-a","highlight-b"]','["亮点A","亮点B"]','year-round','全年可订',26,0,'published',0,0,NOW(),NOW()),
('pkg-demo-013','Demo Package 013','示例套餐 013','demo-package-13','Demo English description 013','中文示例描述 013','Short demo 013','简短示例 013',1065000,'IDR',5,'days','["demo","test"]','["示例","测试"]','yogyakarta','日惹','["hotel","breakfast"]','["酒店","早餐"]','["flights"]','["机票"]','["highlight-a","highlight-b"]','["亮点A","亮点B"]','year-round','全年可订',27,0,'published',0,0,NOW(),NOW()),
('pkg-demo-014','Demo Package 014','示例套餐 014','demo-package-14','Demo English description 014','中文示例描述 014','Short demo 014','简短示例 014',1070000,'IDR',6,'days','["demo","test"]','["示例","测试"]','komodo','科莫多','["hotel","breakfast"]','["酒店","早餐"]','["flights"]','["机票"]','["highlight-a","highlight-b"]','["亮点A","亮点B"]','year-round','全年可订',28,0,'published',0,0,NOW(),NOW()),
('pkg-demo-015','Demo Package 015','示例套餐 015','demo-package-15','Demo English description 015','中文示例描述 015','Short demo 015','简短示例 015',1075000,'IDR',7,'days','["demo","test"]','["示例","测试"]','jakarta','雅加达','["hotel","breakfast"]','["酒店","早餐"]','["flights"]','["机票"]','["highlight-a","highlight-b"]','["亮点A","亮点B"]','year-round','全年可订',29,0,'published',0,0,NOW(),NOW()),
('pkg-demo-016','Demo Package 016','示例套餐 016','demo-package-16','Demo English description 016','中文示例描述 016','Short demo 016','简短示例 016',1080000,'IDR',8,'days','["demo","test"]','["示例","测试"]','bandung','万隆','["hotel","breakfast"]','["酒店","早餐"]','["flights"]','["机票"]','["highlight-a","highlight-b"]','["亮点A","亮点B"]','year-round','全年可订',30,0,'published',0,0,NOW(),NOW()),
('pkg-demo-017','Demo Package 017','示例套餐 017','demo-package-17','Demo English description 017','中文示例描述 017','Short demo 017','简短示例 017',1085000,'IDR',9,'days','["demo","test"]','["示例","测试"]','bromo','布罗莫','["hotel","breakfast"]','["酒店","早餐"]','["flights"]','["机票"]','["highlight-a","highlight-b"]','["亮点A","亮点B"]','year-round','全年可订',31,0,'published',0,0,NOW(),NOW()),
('pkg-demo-018','Demo Package 018','示例套餐 018','demo-package-18','Demo English description 018','中文示例描述 018','Short demo 018','简短示例 018',1090000,'IDR',10,'days','["demo","test"]','["示例","测试"]','raja-ampat','四王群岛','["hotel","breakfast"]','["酒店","早餐"]','["flights"]','["机票"]','["highlight-a","highlight-b"]','["亮点A","亮点B"]','year-round','全年可订',32,0,'published',0,0,NOW(),NOW()),
('pkg-demo-019','Demo Package 019','示例套餐 019','demo-package-19','Demo English description 019','中文示例描述 019','Short demo 019','简短示例 019',1095000,'IDR',11,'days','["demo","test"]','["示例","测试"]','sumba','松巴','["hotel","breakfast"]','["酒店","早餐"]','["flights"]','["机票"]','["highlight-a","highlight-b"]','["亮点A","亮点B"]','year-round','全年可订',33,0,'published',0,0,NOW(),NOW()),
('pkg-demo-020','Demo Package 020','示例套餐 020','demo-package-20','Demo English description 020','中文示例描述 020','Short demo 020','简短示例 020',1100000,'IDR',12,'days','["demo","test"]','["示例","测试"]','belitung','勿里洞','["hotel","breakfast"]','["酒店","早餐"]','["flights"]','["机票"]','["highlight-a","highlight-b"]','["亮点A","亮点B"]','year-round','全年可订',34,0,'published',0,0,NOW(),NOW());

INSERT INTO package_images(id,package_id,url,alt,`order`,is_cover,created_at,updated_at) VALUES
('img-demo-001-1','pkg-demo-001','https://images.pexels.com/photos/346885/pexels-photo-346885.jpeg','Demo 001',1,1,NOW(),NOW()),
('img-demo-001-2','pkg-demo-001','https://images.pexels.com/photos/1430676/pexels-photo-1430676.jpeg','Demo 001',2,0,NOW(),NOW()),
('img-demo-001-3','pkg-demo-001','https://images.pexels.com/photos/2404370/pexels-photo-2404370.jpeg','Demo 001',3,0,NOW(),NOW());
-- (Add minimal images only for first package to keep seed small)
