-- Seed 20 Travel Packages - Final Correct Version
-- All fields as JSON arrays where needed

INSERT INTO packages (id, title, slug, description, short_description, price, currency, duration, duration_unit, destination, included, excluded, highlights, availability, max_participants, featured, status, view_count, inquiry_count, categories, created_at, updated_at) VALUES
('pkg-001', 'Bali Paradise - 5 Days', 'bali-paradise-5-days', 'Experience authentic Balinese culture with temple visits, beach relaxation, and traditional villages.', '5-day cultural tour', 7500000, 'IDR', 5, 'days', 'Bali', '["Accommodation","Breakfast","Guide","Tickets"]', '["Flights","Lunch","Dinner"]', '["Tanah Lot Temple","Ubud Rice Terraces","Dance Show"]', 'Daily', 15, 1, 'published', 156, 23, '["Beach","Culture"]', datetime('now'), datetime('now')),

('pkg-002', 'Raja Ampat Diving - 7 Days', 'raja-ampat-diving-7-days', 'World-class diving in the most biodiverse marine area with manta rays and pristine reefs.', '7-day diving expedition', 25000000, 'IDR', 7, 'days', 'Raja Ampat', '["Flights","Liveaboard","Meals","10+ Dives","Equipment"]', '["Intl Flights","Nitrox","Tips"]', '["10+ Dive Sites","Manta Rays","Coral Reefs","Piaynemo"]', 'Weekly', 10, 1, 'published', 89, 12, '["Diving","Adventure"]', datetime('now'), datetime('now')),

('pkg-003', 'Komodo Island Trek - 3 Days', 'komodo-island-trekking', 'Trek to see Komodo dragons, snorkel at Pink Beach, and climb Padar Island.', '3-day Komodo adventure', 4500000, 'IDR', 3, 'days', 'Labuan Bajo', '["Boat","Meals","Equipment","Park Fees","Guide"]', '["Hotel","Flights","Drinks"]', '["Komodo Dragons","Pink Beach","Manta Point","Padar Island"]', 'Daily', 12, 1, 'published', 234, 45, '["Adventure","Wildlife"]', datetime('now'), datetime('now')),

('pkg-004', 'Bromo Sunrise Tour - 2 Days', 'bromo-sunrise-tour', 'Witness magical sunrise at Mount Bromo and explore the volcanic crater.', '2-day Bromo sunrise', 2500000, 'IDR', 2, 'days', 'Malang', '["Transport","Hotel","Breakfast","Jeep","Guide"]', '["Flights","Lunch","Dinner","Horse"]', '["Sunrise View","Crater Trek","Jeep Safari","Sand Sea"]', 'Daily', 20, 0, 'published', 312, 67, '["Mountain","Adventure"]', datetime('now'), datetime('now')),

('pkg-005', 'Yogyakarta Heritage - 4 Days', 'yogyakarta-heritage-4-days', 'Explore Borobudur and Prambanan temples, learn batik making.', '4-day cultural heritage', 3800000, 'IDR', 4, 'days', 'Yogyakarta', '["Hotel","Breakfast","Transport","Tickets","Workshop"]', '["Flights","Lunch","Dinner","Shopping"]', '["Borobudur","Prambanan","Batik Making","Kraton Palace"]', 'Daily', 18, 1, 'published', 421, 89, '["Culture","Heritage"]', datetime('now'), datetime('now')),

('pkg-006', 'Lombok Beach Escape - 5 Days', 'lombok-beach-escape', 'Relax on pristine beaches, hike to waterfalls, visit Gili Islands.', '5-day beach getaway', 5200000, 'IDR', 5, 'days', 'Lombok', '["Hotel","Breakfast","Transport","Boat","Trek"]', '["Flights","Meals","Activities"]', '["Senggigi Beach","Waterfall","Gili Islands","Villages"]', 'Daily', 16, 0, 'published', 178, 34, '["Beach","Nature"]', datetime('now'), datetime('now')),

('pkg-007', 'Lake Toba Highland - 4 Days', 'lake-toba-highland', 'Discover Lake Toba, visit Batak villages, enjoy mountain air.', '4-day highland tour', 4200000, 'IDR', 4, 'days', 'North Sumatra', '["Hotel","Breakfast","Ferry","Guide","Tours"]', '["Flights","Lunch","Dinner","Shopping"]', '["Lake Cruise","Samosir Island","Batak Houses","Hot Springs"]', 'Daily', 15, 0, 'published', 145, 28, '["Nature","Culture"]', datetime('now'), datetime('now')),

('pkg-008', 'Gili Islands Hopping - 3 Days', 'gili-islands-hopping', 'Explore Gili Trawangan, Meno, and Air with turtle snorkeling.', '3-day island hopping', 3500000, 'IDR', 3, 'days', 'Gili Islands', '["Hotel","Breakfast","Boat","Equipment"]', '["Flights","Lunch","Dinner","Bicycle"]', '["Island Hopping","Turtle Snorkeling","Beach Party","Sunset"]', 'Daily', 14, 1, 'published', 267, 52, '["Beach","Snorkeling"]', datetime('now'), datetime('now')),

('pkg-009', 'Toraja Funeral Ceremony - 5 Days', 'toraja-funeral-ceremony', 'Witness unique Torajan funeral ceremonies and traditional culture.', '5-day cultural tour', 6800000, 'IDR', 5, 'days', 'Tana Toraja', '["Hotel","Meals","Transport","Guide","Fees"]', '["Flights","Offerings","Tips"]', '["Funeral Ceremony","Tongkonan","Rock Graves","Market"]', 'Selected', 12, 0, 'published', 98, 15, '["Culture","Heritage"]', datetime('now'), datetime('now')),

('pkg-010', 'Banda Islands Spice Route - 6 Days', 'banda-islands-spice', 'Follow spice trade route, dive and explore colonial forts.', '6-day historical tour', 12000000, 'IDR', 6, 'days', 'Banda Islands', '["Flights","Hotel","Meals","Diving","Tours"]', '["Personal","Tips","Extra Dives"]', '["Spice Plantations","Fort Belgica","Diving","Nutmeg"]', 'Weekly', 10, 0, 'published', 67, 9, '["History","Diving"]', datetime('now'), datetime('now')),

('pkg-011', 'Java Coffee Trail - 4 Days', 'java-coffee-trail', 'Journey through coffee plantations, learn roasting and tasting.', '4-day coffee tour', 3200000, 'IDR', 4, 'days', 'Central Java', '["Hotel","Breakfast","Tours","Workshop","Samples"]', '["Flights","Lunch","Dinner","Purchase"]', '["Plantation Tour","Roasting Workshop","Tasting","Village"]', 'Daily', 15, 0, 'published', 123, 21, '["Culture","Food"]', datetime('now'), datetime('now')),

('pkg-012', 'Nias Island Surfing - 5 Days', 'nias-island-surfing', 'Catch world-class waves at Lagundri Bay, see stone jumping.', '5-day surf trip', 5800000, 'IDR', 5, 'days', 'Nias Island', '["Hotel","Breakfast","Boat","Guide"]', '["Flights","Board","Meals","Lessons"]', '["Lagundri Bay","Stone Jumping","Villages","Beach"]', 'Daily', 12, 0, 'published', 89, 14, '["Surfing","Adventure"]', datetime('now'), datetime('now')),

('pkg-013', 'Thousand Islands - 2 Days', 'thousand-islands-snorkeling', 'Quick Jakarta getaway with snorkeling and beach time.', '2-day island escape', 2800000, 'IDR', 2, 'days', 'Thousand Islands', '["Boat","Cottage","Meals","Equipment","BBQ"]', '["Marina Transport","Extra Activities"]', '["Coral Snorkeling","Island Hopping","BBQ","Kayaking"]', 'Daily', 16, 0, 'published', 234, 48, '["Beach","Snorkeling"]', datetime('now'), datetime('now')),

('pkg-014', 'Belitung Granite Beach - 4 Days', 'belitung-granite-beaches', 'Explore granite formations and beaches from Indonesian movies.', '4-day island tour', 4800000, 'IDR', 4, 'days', 'Belitung', '["Hotel","Breakfast","Boat","Guide"]', '["Flights","Lunch","Dinner","Gear"]', '["Tanjung Tinggi","Island Hopping","Granite Rocks","School"]', 'Daily', 14, 1, 'published', 156, 29, '["Beach","Photography"]', datetime('now'), datetime('now')),

('pkg-015', 'Papua Tribal Expedition - 8 Days', 'papua-tribal-expedition', 'Deep expedition to meet Dani tribe in Papua highlands.', '8-day tribal tour', 28000000, 'IDR', 8, 'days', 'Wamena', '["Flights","Accommodation","Meals","Guide","Permits"]', '["Gear","Tips","Offerings"]', '["Dani Tribe","Baliem Valley","Ceremonies","Mummy Cave"]', 'Selected', 8, 0, 'draft', 34, 3, '["Culture","Adventure"]', datetime('now'), datetime('now')),

('pkg-016', 'Malang City & Beaches - 3 Days', 'malang-city-beaches', 'Explore colorful city, apple orchards, and southern beaches.', '3-day city & beach', 3100000, 'IDR', 3, 'days', 'Malang', '["Hotel","Breakfast","Transport","Tickets"]', '["Flights","Meals","Shopping","Activities"]', '["Colorful Village","Apple Picking","Beach","City Tour"]', 'Daily', 16, 0, 'published', 189, 37, '["City","Beach"]', datetime('now'), datetime('now')),

('pkg-017', 'Derawan Diving - 6 Days', 'derawan-diving-6-days', 'Dive with whale sharks, turtles, and jellyfish in crystal waters.', '6-day whale shark diving', 14500000, 'IDR', 6, 'days', 'Derawan', '["Flights","Resort","Meals","Equipment","Boat"]', '["Certification","Computer","Tips"]', '["Whale Sharks","Jellyfish Lake","Turtle Nesting","Mantas"]', 'Weekly', 10, 1, 'published', 112, 18, '["Diving","Wildlife"]', datetime('now'), datetime('now')),

('pkg-018', 'Tanjung Puting Orangutan - 4 Days', 'tanjung-puting-orangutan', 'Cruise on klotok boat to see wild orangutans at feeding sites.', '4-day orangutan tour', 8500000, 'IDR', 4, 'days', 'Central Kalimantan', '["Flights","Klotok","Meals","Guide","Permits"]', '["Tips","Drinks","Personal"]', '["Wild Orangutans","Klotok Boat","Night Safari","Monkeys"]', 'Daily', 12, 1, 'published', 198, 32, '["Wildlife","Nature"]', datetime('now'), datetime('now')),

('pkg-019', 'Wakatobi Diving Paradise - 7 Days', 'wakatobi-diving-paradise', 'Dive in world-best coral reefs with incredible biodiversity.', '7-day diving paradise', 22000000, 'IDR', 7, 'days', 'Wakatobi', '["Flights","Resort","Meals","Unlimited Diving","Equipment"]', '["Nitrox","Tips","Purchase"]', '["World Class Reefs","50+ Sites","Macro Photo","Wall Diving"]', 'Weekly', 10, 1, 'published', 76, 11, '["Diving","Marine"]', datetime('now'), datetime('now')),

('pkg-020', 'Bintan Beach Resort - 3 Days', 'bintan-beach-resort', 'Luxury beach getaway with resort stay, water sports, and spa.', '3-day luxury escape', 4800000, 'IDR', 3, 'days', 'Bintan', '["Ferry","Resort","Breakfast","Welcome Drink","Pool"]', '["Meals","Water Sports","Spa","Golf"]', '["Private Beach","Water Sports","Spa Treatment","Golf"]', 'Daily', 20, 0, 'published', 267, 54, '["Beach","Relaxation"]', datetime('now'), datetime('now'));